# Adapted from Calin Tat's Minimal theme: https://github.com/calintat/minimal/

baseURL = "/"
languageCode = "en-us"
title = "Geodemographics of British Streets"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

pluralizelisttitles = false

[params]
    author = "Peter Prescott"
    description = "My PhD process and other assorted projects"
    descriptionLink = "https://www.github.com/peterprescott"
    githubUsername = "peterprescott"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Libre Baskerville" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"

[[menu.main]]
	url = "/about/"
	name = "About"
	weight = 1

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 2
 
[[menu.main]]
    url = "/notes/"
    name = "Notes"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/


[[menu.icon]]
    url = "https://peter.prescott.org.uk"
    name = "fas fa-male"
    weight = 1

[[menu.icon]]
    url = "https://news.ycombinator.com/user?id=peterprescott"
    name = "fab fa-hacker-news-square"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/peter_prescott"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://github.com/peterprescott"
    name = "fab fa-github"
    weight = 4
